export const categories = [
	{
		id: 1,
		name: 'All Products',
		src: 'https://images.pexels.com/photos/2473586/pexels-photo-2473586.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-allProducts.webp',
		link: '/list?cat=test',
	},
	{
		id: 2,
		name: 'Featured',
		src: 'https://images.pexels.com/photos/20471171/pexels-photo-20471171/free-photo-of-moda-mujer-planta-hojas.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-featured.webp',
		link: '/list?cat=test',
	},
	{
		id: 3,
		name: 'Accessories',
		src: 'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-accessories.webp',
		link: '/list?cat=test',
	},
	{
		id: 4,
		name: 'Jeans',
		src: 'https://images.pexels.com/photos/16850074/pexels-photo-16850074/free-photo-of-mujer-roto-sentado-tejanos.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-jeans.webp',
		link: '/list?cat=test',
	},
	{
		id: 5,
		name: 'Skirts',
		src: 'https://images.pexels.com/photos/1857375/pexels-photo-1857375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-skirts.webp',
		link: '/list?cat=test',
	},
	{
		id: 6,
		name: 'Sweaters',
		src: 'https://images.pexels.com/photos/5407259/pexels-photo-5407259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-sweaters.webp',
		link: '/list?cat=test',
	},
	{
		id: 7,
		name: 'T-shirts',
		src: 'https://images.pexels.com/photos/2328051/pexels-photo-2328051.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-T-shirts.webp',
		link: '/list?cat=test',
	},
	{
		id: 8,
		name: 'Coats',
		src: 'https://images.pexels.com/photos/20434986/pexels-photo-20434986/free-photo-of-mujer-modelo-maqueta-chaqueta.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-coats.webp',
		link: '/list?cat=test',
	},
	{
		id: 9,
		name: 'Hats',
		src: 'https://images.pexels.com/photos/2613260/pexels-photo-2613260.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-hats.webp',
		link: '/list?cat=test',
	},
	{
		id: 10,
		name: 'Home',
		src: 'https://images.pexels.com/photos/5375975/pexels-photo-5375975.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		src2: '/assets/categories/categories-home.webp',
		link: '/list?cat=test',
	},
]
